### ISSUE TITLE
Need an example for self signed certificates

### ISSUE THREAD

**Issue by brucealthompson** [cloudamqp/php-amqplib-ssl-example#1]
This example is interesting  but I believe it is not relevant for self signed certificates.

Here is a link to an example of the use of php-amqplib for self signed certificates:
https://stackoverflow.com/questions/47718776/uncaught-errorexception-stream-socket-client-ssl-handshake-timed-out#new-answer?newreg=75bc83f6cb024406a02b87c8bce9c25a

Unfortunately, the code sample shown by this link does not work. I have exactly the same issue with my php code which was written the same way. Since this stackoverflow issue has never been resolved, I assume php-amqplib does not actually work with self signed certificates. Please prove me wrong.

**Comment by dentarg** [comment]
I think you should raise this concern at https://github.com/php-amqplib/php-amqplib or at https://groups.google.com/g/php-amqplib-devel
